eut_fast_lio_node:
    ros__parameters:
        # General parameters
        map_frame_id:    "odom"
        target_frame_id: "base_footprint"
        base_frame_id:   "base_footprint"
        sensor_frame_id: "livox_mid360_lidar_link"

        feature_extract_enable: 0
        point_filter_num: 2
        max_iteration: 3
        filter_size_surf: 0.2
        filter_size_map:  0.2 
        cube_side_length: 1000.0
        runtime_pos_log_enable: false

        sensor_extrinsic_T: [1.33, 0.0, 0.329]
        sensor_extrinsic_R: [0.8661, 0.0, 0.5,
                             0.0, 1.0, 0.0,
                             -0.5, 0.0, 0.8661]

        common:
            lid_topic:  "/livox/lidar"
            imu_topic:  "/livox/imu"
            time_sync_en: false            # ONLY turn on when external time synchronization is really not possible
            time_offset_lidar_to_imu: 0.1  # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                           # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

        preprocess:
            lidar_type: 4                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 4 for MID360 LiDAR
            scan_line: 4
            blind: 1.0

        mapping:
            acc_cov: 0.1
            gyr_cov: 0.1
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            fov_degree:    360.0
            det_range:     450.0
            extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic,
            extrinsic_T: [ 0.011, 0.02329, -0.04412]
            extrinsic_R: [1.0, 0.0, 0.0,
                          0.0, 1.0, 0.0,
                          0.0, 0.0, 1.0]
        publish:
           registered_cloud:  true
           tf:                true       
           path:              true      
           map:               true  