eut_fast_lio_node:
    ros__parameters:
        # General parameters
        map_frame_id:    "odom"
        target_frame_id: "base_footprint"
        base_frame_id:   "base_footprint"
        sensor_frame_id: "rslidar_link"

        feature_extract_enable: 0
        point_filter_num: 3
        max_iteration: 3
        filter_size_surf: 0.5
        filter_size_map:  0.5 
        cube_side_length: 1000.0
        runtime_pos_log_enable: false

        sensor_extrinsic_T: [ 1.75, 0.0, 0.7]
        sensor_extrinsic_R: [1.0, 0.0, 0.0,
                             0.0, 1.0, 0.0,
                             0.0, 0.0, 1.0]

        common:
            lid_topic:  "/rslidar_converted"
            imu_topic:  "/um7/imu/data"
            time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
            time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                        # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

        preprocess:
            lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
            scan_line: 16
            scan_rate: 10                # only need to be set for velodyne, unit: Hz,
            timestamp_unit: 2.0            # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
            blind: 2.0

        mapping:
            acc_cov: 0.1
            gyr_cov: 0.1
            b_acc_cov: 0.01
            b_gyr_cov: 0.01
            fov_degree:    360.0
            det_range:     450.0
            extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic,
            extrinsic_T: [ 0.0, 0.0, 0.0615]
            extrinsic_R: [1.0, 0.0, 0.0,
                          0.0, -1.0, 0.0,
                          0.0, 0.0, -1.0]
        publish:
           registered_cloud:  true
           tf:                true       
           path:              true      
           map:               false  