ekf_filter_node_local:
  ros__parameters:

    odom_frame: odom
    base_link_frame: base_footprint
    map_frame: map
    world_frame: map

    frequency: 50.0
    publish_tf: false
    two_d_mode: true

    # x, y, z,
    # roll, pitch, yaw,
    # vx, vy, vz,
    # vroll, vpitch, vyaw,
    # ax, ay, az
    odom0: /r4c_tractor/wheel_odom
    odom0_queue_size: 10
    odom0_differential: false
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]