std_msgs/Header header

uint8 NOT_AVAILABLE=3
uint8 RESERVED=2
uint8 LAMP_ON=1
uint8 LAMP_OFF=0

uint8 protect_lamp_status
uint8 amber_warning_lamp_status
uint8 red_stop_lamp_state
uint8 malfunction_indicator_lamp_status

uint8 UNAVAILABLE_DO_NOT_FLASH=3
uint8 FAST_FLASH=1
uint8 SLOW_FLASH=0

uint8 flash_protect_lamp
uint8 flash_amber_warning_lamp
uint8 flash_red_stop_lamp
uint8 flash_malfunc_indicator_lamp