ackermann_twist_to_joint_states:
  ros__parameters:
    front_left_joint: front_left_joint
    front_right_joint: front_right_joint
    rear_left_joint: rear_left_joint
    rear_right_joint: rear_right_joint
    left_steering_joint: left_steering_joint
    right_steering_joint: right_steering_joint
    front_wheel_radius: 0.425
    rear_wheel_radius: 0.65
    wheelbase: 2.1804
    front_wheel_spacing: 1.176
    rear_wheel_spacing: 1.176
    first_twist_timeout: 120.0
    joint_states_topic: joint_states
    twist_topic: r4c_tractor/vel
