joy:
  ros__parameters:
    dev: /dev/input/js0
    deadzone: 0.1
    autorepeat_rate: 30.0 

teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: true
    enable_button: 5
    enable_turbo_button: 10
    axis_linear:
      x: 1
      y: -1 # disable
      z: -1 # disabled
    scale_linear:
      x: 1.0
      y: 0.0
      z: 0.0
    scale_linear_turbo:
      x: 1.5
      y: 0.0
      z: 0.0
    axis_angular:
      roll: -1  # disabled
      pitch: -1 # disabled
      yaw: 0
    scale_angular:
      roll: 0.0
      pitch: 0.0
      yaw: 0.5
    scale_angular_turbo:
      roll: 0.0
      pitch: 0.0
      yaw: 1.0
