livox_trunk_detector:
  ros__parameters:
    ground_frame: "ground"
    target_frame: "base_footprint"
    output_frame: "base_link"
    use_ground_detection: true
    ground_min_x: -20.0
    ground_max_x: 20.0
    ground_min_y: -3.0
    ground_max_y: 3.0
    ground_min_z: -1.0
    ground_max_z: 1.0
    ground_ransac_max_iter: 500
    ground_ransac_dist_thresh: 0.1
    ground_voxel_size: 0.01
    ground_min_point_quantity: 1000
    ground_thresh: 20.0
    ground_max_iters: 10
    max_dist_to_ground: 0.5
    x_min_pcl_target_frame: -20.0
    x_max_pcl_target_frame: 20.0
    y_min_pcl_target_frame: -2.20
    y_max_pcl_target_frame: 2.20
    z_min_pcl_target_frame: 0.05
    z_max_pcl_target_frame: 0.40
    x_min_pcl_ground_frame: -20.0
    x_max_pcl_ground_frame: 20.0
    y_min_pcl_ground_frame: -2.20
    y_max_pcl_ground_frame: 2.20
    z_min_pcl_ground_frame: 0.05
    z_max_pcl_ground_frame: 0.40
    num_horizontal_slices: 5
    trunk_voxel_size: 0.01
    cluster_min_size: 5
    cluster_max_size: 100
    cluster_tolerance: 0.1
    min_trunk_layers: 3
    max_skipped_layers: 1
    trunk_xy_tolerance: 0.1
    centroid_min_width: 0.01
    centroid_max_width: 0.1
    ror_min_neighbors: 2
    ror_radius_search: 0.03