# config para gamepad
joy:
  ros__parameters:
    dev: /dev/input/js0
    deadzone: 0.1
    autorepeat_rate: 30.0 # The AGCBox expects commands at this rate

ackermann_teleoperation:
  ros__parameters:
    dist_betw_axes: 2.1804 # m
    dist_betw_axis_wheels: 1.176 # m
    max_forward_vel: 1.5 # m/s
    max_rear_vel: 0.0    # m/s, the tractor must change gears to go backward. We can't change gears by-wire, so we can't command the tractor to go backward. So we set it to 0.
    min_turning_radius: 2.0 # m, max_steering_angle = atan(dis_betw_axes/Rmin) = atan(2.180/3) = 36 deg
    lin_vel_compression_coeff: 0.5
    enable_button: 5
    lin_vel_compression_coeff_button: 4
    lin_vel_axis: 1
    steering_angle_axis: 3
